# azure-pipelines.yml
trigger:
  - main

parameters:
  - name: targetEnvironment
    displayName: "Select Deployment Environment"
    type: string
    default: sandbox
    values:
      - sandbox
      - production

variables:
  # Set loginUrl based on environment
  name: loginUrl
  ${{ if eq(parameters.targetEnvironment, 'production') }}:
    value: 'https://login.salesforce.com'
  ${{ else }}:
    value: 'https://test.salesforce.com'

stages:
  - stage: DeploySalesforceData
    displayName: "Deploy Salesforce Data in JSON Format"
    jobs:
      - job: DataDeployment
        displayName: "Salesforce Device Login and JSON Data Deployment"
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          # 1. Install Node.js
          - task: NodeTool@0
            inputs:
              versionSpec: '16.x'
            displayName: 'Install Node.js'

          # 2. Install Salesforce CLI globally
          - script: |
              echo "Installing Salesforce CLI..."
              npm install sfdx-cli --global
            displayName: 'Install Salesforce CLI'

          # 3. Authenticate to Salesforce using device login
          - script: |
              echo "Authenticating to Salesforce on URL: $(loginUrl)"
              sfdx force:auth:device:login -r $(loginUrl) --setdefaultusername
            displayName: 'Salesforce Device Login'

          # 4. Deploy JSON data using the Salesforce CLI
          # Ensure that your JSON file (sampleData.json) is in the repository root or adjust the path accordingly.
          - script: |
              echo "Deploying Salesforce data from JSON..."
              sfdx force:data:tree:import -p sampleData.json
            displayName: 'Deploy Salesforce JSON Data'

          # Optional: Additional steps for production environments
          - ${{ if eq(parameters.targetEnvironment, 'production') }}:
            - script: |
                echo "Production environment detected. Running post-deployment validations..."
                # Add any additional production-specific steps here.
              displayName: 'Production Post-Deployment Steps'
