# azure-pipelines.yml
trigger:
  - main

parameters:
  - name: targetEnvironment
    displayName: "Select Deployment Environment"
    type: string
    default: sandbox
    values:
      - sandbox
      - production

variables:
  - name: loginUrl
    ${{ if eq(parameters.targetEnvironment, 'production') }}:
      value: 'https://login.salesforce.com'
    ${{ else }}:
      value: 'https://test.salesforce.com'

stages:
  - stage: DeploySalesforce
    displayName: "Deploy Salesforce Data"
    jobs:
      - job: SalesforceDeployment
        displayName: "Salesforce Authentication and Deployment"
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          # 1. Install Node.js so that npm is available
          - task: NodeTool@0
            inputs:
              versionSpec: '16.x'
            displayName: 'Install Node.js'

          # 2. Install the Salesforce CLI using npm
          - script: |
              echo "Verifying npm version..."
              npm --version
              echo "Installing Salesforce CLI globally..."
              npm install --global sfdx-cli
            displayName: 'Install Salesforce CLI'

          # 3. Authenticate to Salesforce using device login
          - script: |
              echo "Checking Salesforce CLI version..."
              sfdx --version
              echo "Authenticating to Salesforce on URL: $(loginUrl)"
              sfdx force:auth:device:login -r $(loginUrl) --setdefaultusername
            displayName: 'Salesforce Device Login'

          # 4. Ensure we are inside the correct Salesforce project directory
          - script: |
              echo "Checking for Salesforce project..."
              if [ ! -f "sfdx-project.json" ]; then
                echo "Error: Not inside a Salesforce DX project! Exiting."
                exit 1
              fi
              echo "Verified: Salesforce DX project found."
            displayName: 'Verify Salesforce DX Project'

          # 5. Deploy with NoTestRun for Sandbox
          - ${{ if ne(parameters.targetEnvironment, 'production') }}:
            - script: |
                echo "Deploying to sandbox environment with NoTestRun..."
                cd $(Build.SourcesDirectory)  # Ensure correct working directory
                sfdx force:source:deploy -p force-app --testlevel NoTestRun
              displayName: 'Deploy Source (NoTestRun)'

          # 6. Deploy with RunAllTests for Production
          - ${{ if eq(parameters.targetEnvironment, 'production') }}:
            - script: |
                echo "Deploying to production environment with RunAllTests..."
                cd $(Build.SourcesDirectory)  # Ensure correct working directory
                sfdx force:source:deploy -p force-app --testlevel RunAllTests
              displayName: 'Deploy Source (RunAllTests)'
